FROM node:8

RUN mkdir /app
WORKDIR /app
                                                                                                                                                                                                                                          
# Install node_modules with yarn

ADD package.json /app

RUN yarn
