# Generated by Django 2.0 on 2018-09-27 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125, verbose_name='title')),
                ('description', models.CharField(blank=True, max_length=250, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('image', models.ImageField(upload_to='products/product_{self.id}/')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='price')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
    ]
